language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t shadfdz/docker-react -f .Dockerfile.dev .

script:
  - docker run -e CI=true shadfdz/docker-react npm run test

  