language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t shadfdz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shadfdz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-demo"
  env: "Dockerreactdemo-env"
  bucket_name: "elasticbeanstalk-us-west-1-822593258676"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

